### ISSUE TITLE
docs/readme: document the 'debug' command

### ISSUE THREAD

**Issue by kcq** [slimtoolkit/slim#372]
We have no info about the 'debug' command in readme. We do have the `DEBUGGING MINIFIED CONTAINERS` section. Need to extend this section to show how to use the 'debug' command in addition to adding the basic command and flag info.

**Comment by shadowshot-x** [comment]
Hi @kcq . I would like to contribute to this. Can you assign me this issue?

**Comment by Omkar0114** [comment]
Hello @kcq, recently started using and exploring Slim, and want to contribute to Slim.
This issue looks good first to start with :) 
Can you assign it to me, I'll start working. Thank you!

**Comment by Omkar0114** [comment]
Hi @kcq  @iximiuz , 
I am trying to work on this issue and experimenting with the docker-slim `debug` command. 
According to my learnings for the `slim debug` command

1. First we have to optimize the image using the `docker-slim build` command (image must present locally)
2. Then we need to start a container of that optimized image for the `debug` purpose
3. Use the `docker-slim debug <container_name>` command to start debugging process
4. Attach the newly created `debugger container` using `docker attach <debugger_container_id>` to inspect and debug the container. 

I have done the above steps, for the 4th step I am getting errors or I should be missing something!
Here are the outputs: 

![image](https://github.com/slimtoolkit/slim/assets/88308267/469afcc4-4324-421f-a089-8d464d3bd0a2)

![image](https://github.com/slimtoolkit/slim/assets/88308267/8cbbeee5-2c99-4105-ab31-35bca3bdc4b7)

Please point out to me what I should be missing.

Thank you :)

**Comment by iximiuz** [comment]
Hi @Omkar0114! Thank you for your effort!

The error message on the attached screenshot contains a hint - the `slim debug` command tries to start a debug container that reuses as many of the target container namespaces as just possible, including the `IPC` namespace. However, by default, in Docker containers are started with the IPC namespace being "non-sharable". A simple workaround is to start the target container using the `docker run` with the `--ipc 'shareable'` flag ([see example in this blog post](https://iximiuz.com/en/posts/containers-vs-pods/)). However, a better way to address this problem is to make the `slim debug` command ignore the IPC namespace if the target is started in a non-sharable mode.

**Comment by kcq** [comment]
@Omkar0114 the `debug` command is still pretty basic and it does require that the target container you are debugging has ipc sharable like Ivan mentioned. This is a great piece of info the `debug` command documentation should capture :-)

The step 4 you mentioned is not really necessary (at least, not when you don't specify a custom CMD info in the command line), but if it works it might be good to mention in the docs too. The main mode for the `debug` command is to interact with the debugged target image through the `slim debug` command terminal/interface.

I assume you are looking at the cli.go file for the `debug` command too. It should give you an idea about the type of parameters that can be passed to the `debug` command. Looks like there's a bug there with the command parameters. It tries to read the target container reference from the `--target` command flag first, but the flag is not configured for the command. Good news the target reference can be specified without any flag name (that's the value that comes after the optional flags when you call the command).

Here's a basic example:

First, start the target container you want to debug (it doesn't need to be minified).

`docker run -it --rm -p 80:80 --ipc 'shareable' --name mytarget nginx`

Second, run the `debug` command:

`slim debug mytarget`

**Comment by Omkar0114** [comment]
Thanks a lot, @iximiuz and @kcq for such detailed information on the `debug` command. I just did a demo of running the `slim debug` command and successfully worked. 
In the README, we do have the `DEBUGGING MINIFIED CONTAINERS`  section. I'll add one example of how to run the `slim debug` command from scratch and also other flags of it and will raise PR soon. 
Thank you :)

**Comment by kcq** [comment]
looking forward to the PR @Omkar0114

**Comment by Omkar0114** [comment]
Hi @kcq we can close this issue now as it resolved.
Thanks for merging my PR 😊 🙌

**Comment by kcq** [comment]
yes, closing
