### ISSUE TITLE
'server' sub-command for the 'registry' command

### ISSUE THREAD

**Issue by kcq** [slimtoolkit/slim#375]
Need to leverage the registry server in the go-containerregistry library ( https://github.com/google/go-containerregistry/tree/main/pkg/registry )

**Comment by jarda-wien** [comment]
I saw the new `server` sub-command being released recently. I went looking for some docs on why to use this but I don't seem to understand the use-case.

What is the difference to the official registry implementation from https://github.com/distribution/distribution or why one might want to use slim's version over the other?

**Comment by kcq** [comment]
> I saw the new `server` sub-command being released recently. I went looking for some docs on why to use this but I don't seem to understand the use-case.
> 
> What is the difference to the official registry implementation from https://github.com/distribution/distribution or why one might want to use slim's version over the other?

it's lightweight, nice for testing and, in some cases, easier to use in a number of local registry user cases (no need to mess with the /etc/hosts file). note that it doesn't have full data persistence, so it's definitely not a full registry good for production use.
