### ISSUE TITLE
Error in the scripted install script

### ISSUE THREAD

**Issue by righettod** [slimtoolkit/slim#448]
Hi,

it's seems that there is an error in the scripted install script:

![image](https://user-images.githubusercontent.com/1573775/211253449-fa2518e1-bff4-4534-8369-80102d3354a5.png)

[Source](https://github.com/slimtoolkit/slim/blob/master/scripts/install-slim.sh#L74)

![image](https://user-images.githubusercontent.com/1573775/211253567-e0c6f555-2251-4b13-bc13-3d3523116f97.png)

It is normal ?

Thanks a lot in advance 😃

**Comment by kcq** [comment]
sorry for the disruption with the script @righettod ! no, that shouldn't happen. the script got updated ahead of the current release where the new names are used for the executables. will be fixed in a day or so

**Comment by righettod** [comment]
Hi @kcq 

No problem at all, its happen 😃 

Thank you very much for this amazing tool and quick feedback about the issue 🥇
