### ISSUE TITLE
Error when using the slim installation script

### ISSUE THREAD

**Issue by righettod** [slimtoolkit/slim#461]
Expected Behavior
=================

Docker Slim is installed correctly by the [install script](https://github.com/slimtoolkit/slim/blob/master/scripts/install-slim.sh).

---
Actual Behavior
=================

The following error occur when the install script is used:

![image](https://user-images.githubusercontent.com/1573775/215297840-38ca9202-e568-4c3c-8c49-7dc37a925858.png)

Occurred on **2023-01-29**.

Content of the archive of the release:

![image](https://user-images.githubusercontent.com/1573775/215297958-cee4c370-ee05-4430-9998-32296fbe9e3b.png)

---
Steps to Reproduce the Problem
===============================

Execute the [install script](https://github.com/slimtoolkit/slim/blob/master/scripts/install-slim.sh).

---
Specifications
=================
  - Version: Latest
  - Platform: Ubuntu latest

**Comment by szh** [comment]
I'm getting the following on Mac OS:
![image](https://user-images.githubusercontent.com/546965/217095781-eda9132a-25fa-408e-8c6d-869569155127.png)
I'm only trying to use the install script because the Homebrew install doesn't seem to work (I'm experiencing #410)

**Comment by righettod** [comment]
It is fixed on my side:

![image](https://user-images.githubusercontent.com/1573775/217322435-b918ffb5-e478-4976-b46f-99064f6db0b2.png)
