### ISSUE TITLE
[docs] Twitter community URL directed to DockerSlim instead of Slim(toolkit)

### ISSUE THREAD

**Issue by Omkar0114** [slimtoolkit/slim#530]
- In the [README.md](https://github.com/slimtoolkit/slim#readme) file, under the community section the Twitter community URL is directed towards the [DockerSlim](https://twitter.com/DockerSlim) instead of [Slim(toolkit)](https://twitter.com/SlimToolkit)

![image](https://github.com/slimtoolkit/slim/assets/88308267/018a949b-3785-4c2e-90f3-41506b764550)

**Comment by Omkar0114** [comment]
Hey @kcq, I can raise a PR for this

**Comment by kcq** [comment]
Sounds good

**Comment by Omkar0114** [comment]
Thanks :)
