### ISSUE TITLE
make build_m1 command not working

### ISSUE THREAD

**Issue by reetasingh** [slimtoolkit/slim#575]
Expected Behavior
=================
make build_m1  should work for mac m1

---
Actual Behavior
=================
```
reeta@Reetas-MacBook-Pro slim % make build_m1
'/Users/reeta/git/slim/scripts/src.build.m1.sh'
~/git/slim ~/git/slim
fatal: No names found, cannot describe anything.
make: *** [build_m1] Error 128
reeta@Reetas-MacBook-Pro slim % 
```

---
Steps to Reproduce the Problem
===============================
 

  1. clone the repo
  2. cd slim
  3. make build_m1

---
Specifications
=================
  - Version: latest source from main
  - Platform: Mac m1

**Comment by kcq** [comment]
thank you for fixing it!

**Comment by reetasingh** [comment]
closed by https://github.com/slimtoolkit/slim/pull/574
