### ISSUE TITLE
Format validation for the --env flag values

### ISSUE THREAD

**Issue by kcq** [slimtoolkit/slim#587]
The "build" and "profile" command have a flag to pass environment variables and the flag values are passed as-is to the downstream container runtime API calls. There's no format validation for the provided values. The values are expected to have the standard environmental variable declaration format (example: ENV_VAR_NAME=ENV_VAR_VALUE)

It'll be good to validate the `--env` flag values to make sure they follow the expected format. If they don't follow the expected format we need to exclude the malformed values from the list of the env vars used later on in the command processing printing to the screen (using the 'execution context' in the command) that the malformed environment variable is discarded/ignored (we should not fail the command execution just because one of the env var values is malformed).

**Comment by vash-knives** [comment]
@kcq , thanks I'm looking into it. When outputting the notice that a `key=variable` is to be excluded, do you want to use "Error" or "Prompt" or "Info"?

**Comment by vash-knives** [comment]
@kcq , will create a PR for you to review, it's a WIP as there are some that might need some clarification.

**Comment by kcq** [comment]
the enhancement is done... closing the ticket
