### ISSUE TITLE
slim 1.40.9 not compatible with new release docker 25.0

### ISSUE THREAD

**Issue by eli-yip** [slimtoolkit/slim#632]
Expected Behavior
=================

slim optimize docker image

---
Actual Behavior
=================

throw an error tell me my docker engine api version is too low, which is not the case at all.

```bash
time="2024-01-20T03:55:39Z" level=error msg="dockerutil.BuildEmptyImage: dockerapi.BuildImage() error = API error (400): client version 1.12 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version\n / output: "
time="2024-01-20T03:55:39Z" level=fatal msg="slim: failure" error="API error (400): client version 1.12 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version\n" stack="goroutine 1 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x5e\ngithub.com/slimtoolkit/slim/pkg/util/errutil.FailOn({0x2fb89e0, 0xc0005aa738})\n\tgithub.com/slimtoolkit/slim/pkg/util/errutil/errutil.go:32 +0x4b\ngithub.com/slimtoolkit/slim/pkg/app/master/inspectors/container.(*Inspector).RunContainer(0xc0001758c0)\n\tgithub.com/slimtoolkit/slim/pkg/app/master/inspectors/container/container_inspector.go:438 +0x774\ngithub.com/slimtoolkit/slim/pkg/app/master/command/build.OnCommand(_, _, {_, _}, _, {_, _}, {_, _}, {0x0, ...}, ...)\n\tgithub.com/slimtoolkit/slim/pkg/app/master/command/build/handler.go:1126 +0x45f2\ngithub.com/slimtoolkit/slim/pkg/app/master/command/build.glob..func1(0xc00046ad80)\n\tgithub.com/slimtoolkit/slim/pkg/app/master/command/build/cli.go:750 +0x5cd0\ngithub.com/urfave/cli/v2.(*Command).Run(0x3fe6620, 0xc00070e600)\n\tgithub.com/urfave/cli/v2@v2.3.0/command.go:163 +0x583\ngithub.com/urfave/cli/v2.(*App).RunContext(0xc0006229c0, {0x2fd6b78?, 0x41bbb40}, {0xc000052070, 0x7, 0x7})\n\tgithub.com/urfave/cli/v2@v2.3.0/app.go:313 +0xaa5\ngithub.com/urfave/cli/v2.(*App).Run(...)\n\tgithub.com/urfave/cli/v2@v2.3.0/app.go:224\ngithub.com/slimtoolkit/slim/pkg/app/master.Run()\n\tgithub.com/slimtoolkit/slim/pkg/app/master/app.go:15 +0x45\nmain.main()\n\tgithub.com/slimtoolkit/slim/cmd/slim/main.go:15 +0x187\n" version="linux/amd64|Transformer|1.40.9|latest|latest"
```

**But when I downgrade my docker version to 24.0.7, it works fine again.**

My system is ubuntu 22.04.

**Comment by kcq** [comment]
@eli-yip thank you for the report! investigating...

**Comment by kcq** [comment]
The issue appears to be limited in certain environments. Doesn't manifest itself everywhere. Still investigating...

**Comment by kcq** [comment]
thank you for sharing the logs @eli-yip ... investigating

**Comment by kcq** [comment]
@eli-yip note that you are trying to minify a base image, `alpine:3.19` and without specifying a lot of extra flags you are likely not going to get what you expect. Base images are like "stem cells", you don't know what they will become and because of that you don't know what needs to be there and what doesn't. When you create an application container image that provides the necessary context about the container image function. Without the application in the container image you have to explicitly indicate what you need and what you don't need in the base image. It is possible to do with the `--include-*`, `--exclude-*` and other `build` command flags (like `--exec`).

**Comment by kcq** [comment]
finally managed to reproduce it and there's a fix for it (will be available in the next release)

**Comment by eli-yip** [comment]
> finally managed to reproduce it and there's a fix for it (will be available in the next release)

@kcq thank you!!!

**Comment by eli-yip** [comment]
> @eli-yip note that you are trying to minify a base image, `alpine:3.19` and without specifying a lot of extra flags you are likely not going to get what you expect. Base images are like "stem cells", you don't know what they will become and because of that you don't know what needs to be there and what doesn't. When you create an application container image that provides the necessary context about the container image function. Without the application in the container image you have to explicitly indicate what you need and what you don't need in the base image. It is possible to do with the `--include-*`, `--exclude-*` and other `build` command flags (like `--exec`).

Thank you for the reminder. I am using the alpine image here to confirm whether the issue is due to compatibility between `Docker` and `Slim`, rather than from my own image build.

To ensure that I've understood you correctly, let me clarify: Even for testing purposes, I should not use a base image, as this would cause errors with `Slim`?

**Comment by kcq** [comment]
@eli-yip it's ok to use a vanilla base image if it's for testing purposes. Just wanted to make sure you are aware of what you'll get there. I also recommend picking a simple shell command with that vanilla base image, so the minified version would have that command and you can see that the minified image works (for that shell command you picked).

Example: `slim build --http-probe=false --entrypoint='ls -lh' alpine`

Then you should be able to use the minified image like this: `docker run -it --rm alpine.slim ls -lh`

**Comment by eli-yip** [comment]
> @eli-yip it's ok to use a vanilla base image if it's for testing purposes. Just wanted to make sure you are aware of what you'll get there. I also recommend picking a simple shell command with that vanilla base image, so the minified version would have that command and you can see that the minified image works (for that shell command you picked).
> 
> Example: `slim build --http-probe=false --entrypoint='ls -lh' alpine`
> 
> Then you should be able to use the minified image like this: `docker run -it --rm alpine.slim ls -lh`

Thank you

**Comment by kcq** [comment]
Docker Engine v25.x broke other things too... waiting for the upstream dependency maintainers to have a fix

**Comment by kcq** [comment]
getting close... will update in a couple of days

**Comment by kcq** [comment]
new release, should support Docker Engine 25.x: https://github.com/slimtoolkit/slim/releases/tag/1.40.11

**Comment by eli-yip** [comment]
> new release, should support Docker Engine 25.x: [`1.40.11` (release)](https://github.com/slimtoolkit/slim/releases/tag/1.40.11)

Works fine, thank you so much.

**Comment by paulcalabro** [comment]
I'm actually still seeing this issue on OSX:

```
slim --version
slim version darwin/arm64|Transformer|1.40.11|latest|latest
```

```
docker --version
Docker version 25.0.3, build 4debf41
```

```
slim build --http-probe=false --entrypoint='ls -lh' alpine
```

```
 error="json: unsupported value: NaN"
 ```

**Comment by paulcalabro** [comment]
Update:

[This worked!](https://github.com/slimtoolkit/slim/issues/646#issuecomment-1969581595)

**Comment by kcq** [comment]
@paulcalabro  With that release you might need to adjust the docker API explicitly, but the latest [version](https://github.com/mintoolkit/mint/releases/tag/1.41.1) shouldn't require it. I couldn't repro the failure with it.
