### ISSUE TITLE
How do I know what the slim tool did to the original image?

### ISSUE THREAD

**Issue by HJX-zhanS** [slimtoolkit/slim#671]
When I used `xray` to analyze before and after slimming, I can extract the files that only existed in the image before slimming from their respective `slim.report.json` files. 

However, the total size of these files is not equal to the image size before slimming minus the image size after slimming. Why?

Can somebody help me? 

Thanks

**Comment by kcq** [comment]
You get additional files that get generated when the dynamic analysis is done with the temporary container. Some of the original files also get mutated at runtime. You can disable this behavior by setting `--include-new` to false. There's also the `--preserve-path` flag that can help you keep the original version of the target file you specify with the flag.
