### ISSUE TITLE
how to pass or preserve network capabilities on files from original docker image ?

### ISSUE THREAD

**Issue by batilak** [slimtoolkit/slim#676]
Expected Behavior
=================
Files copied into slim image must retain network capabilities set in source image

---
Actual Behavior
=================

The app runs fine with source image

With target slim image it gives belwo error

"caps error: capset failure: Operation not permitted (os error 1)"

---
Steps to Reproduce the Problem
===============================
using debian 11

RUN setcap 'cap_net_raw,cap_setpcap=p' "/appdir/app"
USER=1000 

---
Specifications
=================
  - Version:
  - Platform: amd64 Debian11 bullseye-clim (base image)

**Comment by kcq** [comment]
@batilak what version are you using? and just to double check... was it the sensor docker volume for the older version of the app or was it the current version you were using or did you delete all versions of the sensor volume?
