### ISSUE TITLE
Ability to define request timeout for http probe requests

### ISSUE THREAD

**Issue by tylersalminen** [slimtoolkit/slim#705]
It appears that HTTP probe request timeouts are hardcoded through the slim application (set to 30 seconds for probe calls and 10 seconds for crawl calls?). It would be beneficial to my image build pipeline to be able to set these timeouts on a per request basis. For example you could add another option to the HTTP probe commands list like "requestTimeoutSeconds".

**Comment by kcq** [comment]
@tylersalminen should be doable... Overriding the values with custom cli flags will be possible, but for request level overrides you'll need to use custom JSON probe definition. Hope to add it to the next release. Tracked with [this ticket](https://github.com/mintoolkit/mint/issues/44)

**Comment by tylersalminen** [comment]
Awesome, and a JSON definition is what I am indeed using at the moment and where I would expect a new per request timeout to go in. Nevertheless, I am comfortable with just a CLI / Env variable global configuration for the immediate future

**Comment by kcq** [comment]
@tylersalminen try the [new release](https://github.com/mintoolkit/mint/releases/tag/1.41.6) to see how the `----http-probe-client-timeout` and other flags work for you.

**Comment by tylersalminen** [comment]
This is working for me in the new release. Thanks again!
