### ISSUE TITLE
Ability to set HTTP retry count to 0

### ISSUE THREAD

**Issue by tylersalminen** [slimtoolkit/slim#707]
Expected Behavior
=================
When setting DSLIM_HTTP_PROBE_RETRY_COUNT or to 0 --http-probe-retry-count to 0 http probes should retry 0 times

---
Actual Behavior
=================
http probes are instead defaulted to doing using the default of 5 retries instead of doing 0 retries when either setting mentioned above is set to 0

I believe this may be because the http probe is doing retries based on below _and_  maxRetryCount is parsed from CLI / environment coalescing undefined to 0 AND 0 to 0. Thus there is no mechanism to know the difference between an undefined DSLIM_HTTP_PROBE_RETRY_COUNT (for example) vs setting DSLIM_HTTP_PROBE_RETRY_COUNT=0

```go
for i := 0; i < maxRetryCount; i++ {
```

**Comment by kcq** [comment]
In the next release you'll be able to set the flat to -1 to disable retries. Also there'll be a shortcut boolean flag called `--http-probe-retry-off`

**Comment by tylersalminen** [comment]
Awesome thank you!
