### ISSUE TITLE
Add build support for `--tty`

### ISSUE THREAD

**Issue by sigJoe** [slimtoolkit/slim#734]
I have a docker container that only works with Docker's `--tty`, and I want to slim the image down in a single build command. For context, the image contains a scripted job that executes a series of binaries, and one of the binaries simply will not start without a TTY.

This would be a great feature because I want to use slim as a build pipeline step, which I don't think I can do when the process requires multiple terminals.

---
Expected Behavior
=================
I want to use `--tty` in the build command:
i.e. `slim build --http-probe=false --exec "./start.sh" --env-file .env --tty my-image`

---
Actual Behavior
=================
It requires two commands to slim the image.

In one terminal, run:
`slim build --http-probe=false my-image`
In a second terminal, run:
`docker exec --tty --env-file .env slimk_96108_20241210151155  ./start.sh`
Then go back and finish out the first terminal.

---
Specifications
=================
  - Version: `darwin/amd64|Transformer|1.40.11|latest|latest`

**Comment by sigJoe** [comment]
For added context, I tried `--include-shell` and using `script` like  running `slim build --http-probe=false --include-shell --exec 'script -q -c "./start.sh"' --env-file .env --tty my-image`. The app still doesn't work so maybe TTY is the wrong thing to ask for and the tool I'm trying to run is just doing something weird.

**Comment by kcq** [comment]
@sigJoe is `start.sh` the entrypoint in your container? What base image do you use? Is it a Redhat or Redhat like (e.g., Rocky Linux) based image?

**Comment by sigJoe** [comment]
@kcq Correct, `start.sh` is the entrypoint that sets up some config files and runs certain tools in sequence, and I have been using Rocky 9 as a base.

I had also opened a ticket against the tool itself to remove the need for TTY. To my surprise, it got fixed today and now my use case isn't valid anymore. For the curious: it was failing at a part where it waits for the user hit <enter> to quit, similar to how `slim build` does. I'm not clear on the code specifics.

**Comment by kcq** [comment]
@sigJoe this is a good feature... potentially a couple of different flavors. For example, with one flavor you should be able to say that the target app will be "interactive" and here's a sequence of interactions I want you to send. Another flavor can enable an interactive mode where the interactive mode for the target app is proxied/exposed to the person running this tool (this will require explicit user input, which is not always ideal, but it's a common application mode). Created a ticket for this enhancement [here](https://github.com/mintoolkit/mint/issues/90)

**Comment by kcq** [comment]
@sigJoe silly question... is your image related to this image / repo by any chance: https://github.com/Signiant/docker-nagios-base

**Comment by sigJoe** [comment]
@kcq Similar only in that they are both in the realm of monitoring and they have a `start.sh`
