### ISSUE TITLE
Error installing slim toolkit "Cannot open: No such file or directory"

### ISSUE THREAD

**Issue by LumDermaku** [slimtoolkit/slim#737]
**Note**: The installation had been working fine for a long time until yesterday morning.
 

Expected Behavior
=================

Should install properly from https://raw.githubusercontent.com/slimtoolkit/slim/master/scripts/install-slim.sh with command
`curl -sL https://raw.githubusercontent.com/slimtoolkit/slim/master/scripts/install-slim.sh | sudo -E bash -`

---
Actual Behavior
=================

Currently it fails to install on local environment (Ubuntu 24.04) and in CI (Github Actions on Ubuntu 22.04) with the error:

>  - Downloading https://downloads.dockerslim.com/releases/1.40.11/dist_linux.tar.gz
>  - Unpacking dist_linux.tar.gz
> tar: /tmp/tmp.PzywRqGnBL/dist_linux.tar.gz: Cannot open: No such file or directory
> tar: Error is not recoverable: exiting now
>  - Placing slim in /usr/local/bin
> mv: cannot stat '/tmp/tmp.PzywRqGnBL/dist_linux/slim': No such file or directory
> mv: cannot stat '/tmp/tmp.PzywRqGnBL/dist_linux/slim-sensor': No such file or directory
> chmod: cannot access '/usr/local/bin/slim': No such file or directory
> chmod: cannot access '/usr/local/bin/slim-sensor': No such file or directory
>  - Cleaning up
> main: line 88: slim: command not found

---
Steps to Reproduce the Problem
===============================
 

Either
  1. Run `curl -sL https://raw.githubusercontent.com/slimtoolkit/slim/master/scripts/install-slim.sh | sudo -E bash -` on your local machine
  2. Include that command in a github actions step:

>   - name: Install Slim toolkit
>     run: |
>       curl -sL https://raw.githubusercontent.com/slimtoolkit/slim/master/scripts/install-slim.sh | sudo -E bash -

---
Specifications
=================
  - Version: 1.40.11
  - Platform: Ubuntu 24.04, Ubuntu 22.04

**Comment by ldermaku** [comment]
@kcq Could you please look into this? Our builds are failing and we heavily rely on slimtoolkit.

**Comment by kcq** [comment]
> @kcq could you please look into this? Our builds are failing and we heavily rely on slimtoolkit.

@LumDermaku try using the latest version of the install script from here: https://github.com/mintoolkit/mint/blob/master/scripts/install-mint.sh

**Comment by kduret** [comment]
Hi,

the certificate is not valid anymore : 
![image](https://github.com/user-attachments/assets/416b521a-87c7-4917-8ed5-1af78f6805a2)

**Comment by kcq** [comment]
> Hi,
> 
> the certificate is not valid anymore : ![image](https://private-user-images.githubusercontent.com/11978823/396820887-416b521a-87c7-4917-8ed5-1af78f6805a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MTMyNTUsIm5iZiI6MTczNDUxMjk1NSwicGF0aCI6Ii8xMTk3ODgyMy8zOTY4MjA4ODctNDE2YjUyMWEtODdjNy00OTE3LThlZDUtMWFmNzhmNjgwNWEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDA5MDkxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlNzY3MTAyOTkzYzZhN2MyMDE2YTM1ZjlkNGIxZTI4ZGYxZWJhYzY5YTMyNDE2NDU0MDY2M2E1OTIxOWZjMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.L_ZxR4ISbQOhWLo4CJh1ikN0HIvHqsJnwUR_WJi4_LU)

with the latest releases (like [[1.41.7](https://github.com/mintoolkit/mint/releases/tag/1.41.7) , for example) the downloads endpoints is a Github URL and it should have no cert problems

**Comment by saintmalik** [comment]
> @kcq could you please look into this? Our builds are failing and we heavily rely on slimtoolkit.

was experiencing the same thing, if you can self host that bash script, edit it and modify this to download it while bypassing the expired ssl certificate raising that error that isnt allowing the package from downloading 

`
echo " - Downloading ${URL}/${FILENAME}"
TMP_DIR=$(mktemp -d)
curl -Lko "${TMP_DIR}/${FILENAME}" "${URL}/${FILENAME}"
`

**Comment by LumDermaku** [comment]
> > Hi,
> > the certificate is not valid anymore : ![image](https://private-user-images.githubusercontent.com/11978823/396820887-416b521a-87c7-4917-8ed5-1af78f6805a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MTMyNTUsIm5iZiI6MTczNDUxMjk1NSwicGF0aCI6Ii8xMTk3ODgyMy8zOTY4MjA4ODctNDE2YjUyMWEtODdjNy00OTE3LThlZDUtMWFmNzhmNjgwNWEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDA5MDkxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlNzY3MTAyOTkzYzZhN2MyMDE2YTM1ZjlkNGIxZTI4ZGYxZWJhYzY5YTMyNDE2NDU0MDY2M2E1OTIxOWZjMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.L_ZxR4ISbQOhWLo4CJh1ikN0HIvHqsJnwUR_WJi4_LU)
> 
> with the latest releases (like [1.41.7](https://github.com/mintoolkit/mint/releases/tag/1.41.7) , for example) the downloads endpoints is a Github URL and it should have no cert problems

This worked, I adapted the mint command to the one I previously had with slim (small changes) and its working well now.
Thank you @kcq .

**Comment by kcq** [comment]
@LumDermaku let me know if you have any questions and if you'd like to get a personalized session to explore how your app can benefit more from the project and if you have anything on your wishlist in terms of what you wish the project could do.

**Comment by kcq** [comment]
> > @kcq could you please look into this? Our builds are failing and we heavily rely on slimtoolkit.
> 
> was experiencing the same thing, if you can self host that bash script, edit it and modify this to download it while bypassing the expired ssl certificate raising that error that isnt allowing the package from downloading
> 
> ```
> echo " - Downloading ${URL}/${FILENAME}"
> TMP_DIR=$(mktemp -d)
> curl -Lko "${TMP_DIR}/${FILENAME}" "${URL}/${FILENAME}"
> ```
> 
> or better still use this, its an easy one
> 
> ```
> curl -sL https://raw.githubusercontent.com/slimtoolkit/slim/master/scripts/install-slim.sh | sed 's/curl -sLo/curl -Lko/' | sudo -E bash -
> ```

add -k to disable certificate validation is a potential option, but it's better to use the latest script ( https://raw.githubusercontent.com/mintoolkit/mint/master/scripts/install-mint.sh ) to make sure you get the most recent releases.
